version: "3"

services:

  web:
    build: app/docker/python
    env_file:
      - .env
    ports:
      - "5000:5000"
    volumes:
      - .:/usr/src/app
    depends_on:
      - psql
    links:
      - psql

  psql:
    image: postgres:latest
    container_name: flask-psql-cvmaker
    env_file:
      - app/docker/envs/.env
    volumes:
      - ./var/lib/postgresql/data/
    ports:
      - "5433:5433"
